"""Initial schema setup: tenants and users

Revision ID: 6b19ba74664d
Revises: c86f41a25aeb
Create Date: 2026-08-28 21:49:32.042291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b19ba74664d'
down_revision: Union[str, Sequence[str], None] = 'c86f41a25aeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
